import type { Consultation, Creator } from "./types";

const avatar = (seed: string) =>
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;

const room = (seed: string) => `https://picsum.photos/seed/${seed}/400/400`;

export const CREATORS: Creator[] = [
  {
    id: "1",
    name: "노준영",
    bio: "한줄 소개가 들어갑니다.",
    avatar: room("creator-list-1"),
    rating: 4.9,
    reviewCount: 2,
    consultCount: 0,
    followers: "3.2천",
    tags: ["#미니멀", "#우드톤", "#신혼집"],
    styles: ["미니멀&심플", "모던"],
    spaceTypes: ["원룸", "20평대"],
    capacity: 3,
    maxCapacity: 3,
    portfolio: [room("1586024347448"), room("1616484877345"), room("1618221117118"), room("1615876309477")],
    contentGrid: [room("1616484877345"), room("1618221117118"), room("1615876309477"), room("1586024347448"), room("1616484877345"), room("1618221117118")],
  },
  {
    id: "2",
    name: "장원재",
    bio: "밤새 모니터에 튀긴 침이 마르기도 전에.",
    avatar: room("creator-list-2"),
    rating: 5.0,
    reviewCount: 1,
    consultCount: 1,
    followers: "1.8천",
    tags: ["#미니멀", "#우드톤", "#신혼집"],
    styles: ["미니멀&심플", "내추럴"],
    spaceTypes: ["거실", "신혼집"],
    capacity: 2,
    maxCapacity: 3,
    isSpecial: true,
    portfolio: [room("1615876309477"), room("1586024347448"), room("1616484877345"), room("1618221117118")],
    contentGrid: [room("1615876309477"), room("1586024347448"), room("1616484877345"), room("1618221117118"), room("1615876309477"), room("1586024347448")],
  },
  {
    id: "3",
    name: "박의리",
    bio: "의리! 의리! 의리!",
    avatar: room("creator-list-3"),
    rating: 4.7,
    reviewCount: 8,
    consultCount: 2,
    followers: "5.1천",
    tags: ["#미니멀", "#우드톤", "#신혼집"],
    styles: ["북유럽", "내추럴"],
    spaceTypes: ["아파트", "30평대"],
    capacity: 1,
    maxCapacity: 3,
    bookmarked: true,
    portfolio: [room("1618221117118"), room("1615876309477"), room("1586024347448"), room("1616484877345")],
    contentGrid: [room("1618221117118"), room("1615876309477"), room("1586024347448"), room("1616484877345"), room("1618221117118"), room("1615876309477")],
  },
  {
    id: "4",
    name: "구찬모",
    bio: "익스펙토 페트로눔!!",
    avatar: room("creator-list-4"),
    rating: 4.9,
    reviewCount: 5,
    consultCount: 3,
    followers: "2.4천",
    tags: ["#미니멀", "#우드톤", "#신혼집"],
    styles: ["모던", "미니멀&심플"],
    spaceTypes: ["원룸", "10평대"],
    capacity: 0,
    maxCapacity: 3,
    portfolio: [room("1586024347448"), room("1616484877345"), room("1618221117118"), room("1615876309477")],
    contentGrid: [room("1586024347448"), room("1616484877345"), room("1618221117118"), room("1615876309477"), room("1586024347448"), room("1616484877345")],
  },
  {
    id: "5",
    name: "곽춘팔",
    bio: "한줄 소개가 들어갑니다. 전문 분야에 대한 간단한 소개가 여기에 표시됩니다. 최대 50자.",
    avatar: room("creator-detail-5"),
    rating: 4.7,
    reviewCount: 128,
    consultCount: 523,
    followers: "1.2만",
    tags: ["#미니멀", "#우드톤", "#신혼집", "#20평대", "#30평대"],
    styles: ["미니멀&심플", "모던", "내추럴"],
    spaceTypes: ["원룸", "20평대", "30평대"],
    capacity: 2,
    maxCapacity: 3,
    isSpecial: true,
    portfolio: [room("1616484877345"), room("1586024347448"), room("1618221117118"), room("1615876309477")],
    contentGrid: [room("1616484877345"), room("1586024347448"), room("1618221117118"), room("1615876309477"), room("1616484877345"), room("1586024347448")],
  },
];

export const SAMPLE_ANSWER = {
  comment:
    "6평 원룸에 수납을 더하면서도 답답하지 않게 낮은 가구 위주로 골라봤어요.",
  products: [
    {
      id: "p1",
      name: "낮은 3단 서랍장",
      price: 89000,
      image: "/images/event-product-1.png",
      reason: "침대 옆에 딱 맞고 시야를 안 막아요.",
    },
    {
      id: "p2",
      name: "벽걸이 선반 세트",
      price: 32000,
      image: "/images/event-product-2.png",
      reason: "바닥을 안 쓰는 수납이라 좋아요.",
    },
  ],
  budgetTotal: 166000,
  layout3dUrl: "https://ohou.se",
  placementTip: "서랍장은 창가 반대쪽에 두면 좋아요.",
  caution: "서랍장 폭 60cm, 침대 간격을 재보세요.",
  alternativeProducts: [
    {
      id: "alt-p1",
      name: "화이트 2단 서랍장 (대체)",
      price: 69000,
      image: "/images/event-product-1.png",
      reason: "같은 낮은 높이지만 가격이 더 저렴한 대안이에요.",
    },
    {
      id: "alt-p2",
      name: "코너 선반 (대체)",
      price: 28000,
      image: "/images/event-product-2.png",
      reason: "벽걸이 대신 코너를 활용해 수납할 수 있어요.",
    },
  ],
};

export const MOCK_SEED_VERSION = 9;

const SEED_CONSULTATION_IDS = new Set(
  ["c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10", "c11"],
);

/** localStorage에 남은 예전 목업을 최신 시드 데이터로 갱신 (사용자 신청 건은 유지) */
export function mergeConsultationsWithSeed(
  saved: Consultation[],
  savedVersion = 0,
): Consultation[] {
  if (savedVersion !== MOCK_SEED_VERSION) {
    const userCreated = saved.filter((c) => !SEED_CONSULTATION_IDS.has(c.id));
    return [...INITIAL_CONSULTATIONS, ...userCreated];
  }

  const savedMap = new Map(saved.map((c) => [c.id, c]));

  const merged = INITIAL_CONSULTATIONS.map((seed) => {
    const existing = savedMap.get(seed.id);
    if (!existing) return seed;
    return {
      ...seed,
      isRead: existing.isRead,
      status: existing.status,
      rating: existing.rating,
      draftSavedAt: existing.draftSavedAt,
    };
  });

  for (const c of saved) {
    if (!SEED_CONSULTATION_IDS.has(c.id)) merged.push(c);
  }

  return merged;
}

export const INITIAL_CONSULTATIONS: Consultation[] = [
  {
    id: "c1",
    creatorId: "2",
    creatorName: "나다",
    creatorAvatar: avatar("nada"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.06.01",
    dDay: 2,
    status: "WAITING",
    requestForm: {
      spaceType: "원룸",
      members: { adult: 1, child: 0, infant: 0, pet: 0 },
      width: 3.5,
      height: 4.0,
      roomPhotos: [room("1586024347448"), room("1616484877345")],
      ownedFurniture: ["침대", "냉장고", "에어컨", "책상", "의자", "행거"],
      ownedFurniturePhotos: [],
      neededFurniture: ["스탠드", "선반"],
      budget: "50만원",
      style: "미니멀·우드톤",
      requestNote: "",
      referencePhotos: [],
    },
    draftSavedAt: null,
    answer: null,
    isRead: false,
  },
  {
    id: "c4",
    creatorId: "4",
    creatorName: "구찬모",
    creatorAvatar: room("creator-list-4"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.06.01",
    dDay: 2,
    status: "WAITING",
    requestForm: {
      spaceType: "거실",
      members: { adult: 2, child: 0, infant: 0, pet: 0 },
      width: 4.0,
      height: 3.2,
      roomPhotos: [room("1618221117118")],
      ownedFurniture: ["소파", "TV"],
      ownedFurniturePhotos: [],
      neededFurniture: ["커피 테이블", "러그"],
      budget: "30만원~50만원",
      style: "모던",
      requestNote: "",
      referencePhotos: [],
    },
    draftSavedAt: null,
    answer: null,
    isRead: false,
  },
  {
    id: "c2",
    creatorId: "5",
    creatorName: "곽억배",
    creatorAvatar: avatar("buyer1"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.05.30",
    submittedAt: "2026.06.02",
    dDay: 0,
    status: "DONE",
    requestForm: {
      spaceType: "원룸",
      members: { adult: 1, child: 0, infant: 0, pet: 0 },
      width: 3.8,
      height: 4.0,
      roomPhotos: [room("1618221117118")],
      ownedFurniture: ["침대"],
      ownedFurniturePhotos: [],
      neededFurniture: ["소파", "TV장/미디어 선반", "러그"],
      budget: "50만원~100만원",
      style: "모던",
      requestNote: "",
      referencePhotos: [],
    },
    answer: SAMPLE_ANSWER,
    isRead: false,
  },
  {
    id: "c5",
    creatorId: "2",
    creatorName: "장원재",
    creatorAvatar: room("creator-list-2"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.05.27",
    submittedAt: "2026.06.01",
    dDay: 0,
    status: "DONE",
    requestForm: {
      spaceType: "거실",
      members: { adult: 2, child: 0, infant: 0, pet: 0 },
      width: 4.2,
      height: 3.5,
      roomPhotos: [room("1616484877345")],
      ownedFurniture: ["소파"],
      ownedFurniturePhotos: [],
      neededFurniture: ["러그", "조명(스탠드/펜던트)"],
      budget: "30만원~50만원",
      style: "미니멀&심플",
      requestNote: "",
      referencePhotos: [],
    },
    answer: {
      ...SAMPLE_ANSWER,
      comment: "거실 동선을 살리면서 우드톤 포인트를 더한 스타일링을 제안드려요.",
      products: SAMPLE_ANSWER.products.slice(0, 2),
    },
    isRead: false,
  },
  {
    id: "c3",
    creatorId: "3",
    creatorName: "박의리",
    creatorAvatar: avatar("parkuiri"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.05.20",
    submittedAt: "2026.05.24",
    dDay: 0,
    status: "RATED",
    requestForm: {
      spaceType: "침실",
      members: { adult: 2, child: 0, infant: 0, pet: 0 },
      width: 3.5,
      height: 3.2,
      roomPhotos: [room("1615876309477")],
      ownedFurniture: [],
      ownedFurniturePhotos: [],
      neededFurniture: ["침대 프레임", "매트리스", "협탁"],
      budget: "100만원 이상",
      style: "북유럽",
      requestNote: "신혼집 침실 꾸미기",
      referencePhotos: [],
    },
    answer: SAMPLE_ANSWER,
    rating: { score: 5, satisfaction: "positive", comment: "정말 만족스러워요!" },
    isRead: true,
  },
  {
    id: "c6",
    creatorId: "4",
    creatorName: "구찬모",
    creatorAvatar: room("creator-list-4"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.05.15",
    submittedAt: "2026.05.18",
    dDay: 0,
    status: "DONE",
    requestForm: {
      spaceType: "원룸",
      members: { adult: 1, child: 0, infant: 0, pet: 0 },
      width: 3.2,
      height: 3.8,
      roomPhotos: [room("1586024347448")],
      ownedFurniture: ["침대", "책상"],
      ownedFurniturePhotos: [],
      neededFurniture: ["선반"],
      budget: "10만원~20만원",
      style: "모던",
      requestNote: "",
      referencePhotos: [],
    },
    answer: SAMPLE_ANSWER,
    isRead: true,
  },
  {
    id: "c7",
    creatorId: "1",
    creatorName: "노준영",
    creatorAvatar: room("creator-list-1"),
    buyerName: "곽억배",
    buyerAvatar: avatar("buyer1"),
    requestedAt: "2026.05.10",
    submittedAt: "2026.05.12",
    dDay: 0,
    status: "DONE",
    requestForm: {
      spaceType: "거실",
      members: { adult: 2, child: 1, infant: 0, pet: 0 },
      width: 4.5,
      height: 3.6,
      roomPhotos: [room("1618221117118")],
      ownedFurniture: ["소파", "TV"],
      ownedFurniturePhotos: [],
      neededFurniture: ["커피 테이블"],
      budget: "20만원~30만원",
      style: "내추럴",
      requestNote: "",
      referencePhotos: [],
    },
    answer: SAMPLE_ANSWER,
    isRead: true,
  },
  {
    id: "c8",
    creatorId: "5",
    creatorName: "곽억배",
    creatorAvatar: avatar("buyer1"),
    buyerName: "나다",
    buyerAvatar: avatar("nada-buyer"),
    requestedAt: "2026.06.01",
    dDay: 2,
    status: "WAITING",
    draftSavedAt: null,
    requestForm: {
      spaceType: "원룸",
      members: { adult: 1, child: 0, infant: 0, pet: 0 },
      width: 3.5,
      height: 4.0,
      roomPhotos: [room("1586024347448"), room("1616484877345")],
      ownedFurniture: ["침대", "냉장고", "에어컨", "책상", "의자", "행거"],
      ownedFurniturePhotos: [],
      neededFurniture: ["스탠드", "선반"],
      budget: "50만원",
      style: "미니멀·우드톤",
      requestNote: "",
      referencePhotos: [],
    },
    answer: null,
    isRead: false,
  },
  {
    id: "c9",
    creatorId: "5",
    creatorName: "곽억배",
    creatorAvatar: avatar("buyer1"),
    buyerName: "구찬모",
    buyerAvatar: room("creator-list-4"),
    requestedAt: "2026.06.01",
    dDay: 2,
    status: "WAITING",
    draftSavedAt: "2026.06.01",
    requestForm: {
      spaceType: "거실",
      members: { adult: 2, child: 0, infant: 0, pet: 0 },
      width: 4.0,
      height: 3.2,
      roomPhotos: [room("1618221117118")],
      ownedFurniture: ["소파", "TV"],
      ownedFurniturePhotos: [],
      neededFurniture: ["커피 테이블", "러그"],
      budget: "30만원~50만원",
      style: "모던",
      requestNote: "",
      referencePhotos: [],
    },
    answer: null,
    isRead: false,
  },
  {
    id: "c10",
    creatorId: "5",
    creatorName: "곽억배",
    creatorAvatar: avatar("buyer1"),
    buyerName: "박준호",
    buyerAvatar: avatar("junho"),
    requestedAt: "2026.05.25",
    submittedAt: "2026.05.28",
    dDay: 0,
    status: "DONE",
    requestForm: {
      spaceType: "침실",
      members: { adult: 2, child: 0, infant: 0, pet: 0 },
      width: 3.5,
      height: 3.2,
      roomPhotos: [room("1615876309477")],
      ownedFurniture: [],
      ownedFurniturePhotos: [],
      neededFurniture: ["침대 프레임", "협탁"],
      budget: "50만원~100만원",
      style: "북유럽",
      requestNote: "",
      referencePhotos: [],
    },
    answer: SAMPLE_ANSWER,
    isRead: true,
  },
  {
    id: "c11",
    creatorId: "5",
    creatorName: "곽억배",
    creatorAvatar: avatar("buyer1"),
    buyerName: "민지",
    buyerAvatar: avatar("yuna"),
    requestedAt: "2026.05.20",
    submittedAt: "2026.05.23",
    dDay: 0,
    status: "DONE",
    requestForm: {
      spaceType: "원룸",
      members: { adult: 1, child: 0, infant: 0, pet: 0 },
      width: 3.2,
      height: 3.8,
      roomPhotos: [room("1586024347448")],
      ownedFurniture: ["침대"],
      ownedFurniturePhotos: [],
      neededFurniture: ["선반"],
      budget: "20만원~30만원",
      style: "내추럴",
      requestNote: "",
      referencePhotos: [],
    },
    answer: SAMPLE_ANSWER,
    isRead: false,
  },
];

export const EVENT_MOCK = {
  beforeImage: "/images/event-before.png",
  afterImage: "/images/event-after.png",
  creatorName: "곽억배",
  creatorAvatar: avatar("buyer1"),
  creatorSubtitle: "1인 가구를 위한 50만원 맞춤형 오늘의집",
  comment:
    "원룸에 수납을 더하면서도 답답하지 않게 낮은 가구 위주로 골라봤어요.",
  products: [
    {
      id: "ep1",
      name: "낮은 3단 서랍장",
      price: 89000,
      image: "/images/event-product-1.png",
      reason: "침대 옆에 딱 맞고 시야를 안 막아요.",
    },
    {
      id: "ep2",
      name: "벽걸이 선반 세트",
      price: 32000,
      image: "/images/event-product-2.png",
      reason: "바닥을 안 쓰는 수납이라 좋아요.",
    },
  ],
  budgetTotal: 166000,
  layout3dUrl: "https://ohou.se",
  placementTip: "서랍장은 창가 반대쪽에 두면 좋아요.",
  caution: "서랍장 폭 60cm, 침대 간격을 재보세요.",
};

export function getCreator(id: string) {
  return CREATORS.find((c) => c.id === id);
}

export function formatDate() {
  const now = new Date();
  return `${now.getFullYear()}.${String(now.getMonth() + 1).padStart(2, "0")}.${String(now.getDate()).padStart(2, "0")}`;
}

export const MOCK_OHOUSE_PRODUCTS = [
  {
    name: "린넨 2인 소파",
    price: 389000,
    image: room("1586024347448"),
  },
  {
    name: "오크 원목 TV장",
    price: 219000,
    image: room("1615876309477"),
  },
  {
    name: "내추럴 라운드 러그",
    price: 89000,
    image: room("1616484877345"),
  },
  {
    name: "모던 펜던트 조명",
    price: 129000,
    image: room("1618221117118"),
  },
  {
    name: "원목 커피 테이블",
    price: 159000,
    image: room("1586024347448"),
  },
] as const;

export function formatPrice(price: number) {
  return `${price.toLocaleString("ko-KR")}원`;
}
